"""
Baselines — all use the same Ollama SLM for fair comparison.
"""

from llm import query_call, estimate_tokens
import config


def baseline_full_history(all_turns, question, max_tokens=1500):
    """Stuff as many raw turns as fit, truncate oldest first."""
    selected = []
    total = 0
    for turn in reversed(all_turns):
        t = estimate_tokens(turn["text"])
        if total + t > max_tokens:
            break
        selected.insert(0, turn)
        total += t

    history = "\n".join(f"{t['speaker']}: {t['text']}" for t in selected)
    response = query_call([
        {"role": "system", "content": "Answer the question from the conversation history."},
        {"role": "user", "content": f"CONVERSATION:\n{history}\n\nQUESTION: {question}"}
    ])
    return {
        "answer": response,
        "tokens_est": estimate_tokens(history) + estimate_tokens(response) + 50,
        "turns_included": len(selected),
        "turns_dropped": len(all_turns) - len(selected),
    }


def baseline_summary_only(all_turns, question, summary_text=None):
    """Use a pre-generated plain summary (no pointers) to answer."""
    # Summary is pre-generated by the caller using the compiler model
    if not summary_text:
        return {"answer": "(no summary provided)", "tokens_est": 0}

    response = query_call([
        {"role": "system", "content": "Answer the question from the conversation summary."},
        {"role": "user", "content": f"SUMMARY:\n{summary_text}\n\nQUESTION: {question}"}
    ])
    return {
        "answer": response,
        "tokens_est": estimate_tokens(summary_text) + estimate_tokens(response) + 50,
    }


def baseline_sliding_window(all_turns, question, window=None):
    """Only last N turns. Everything older is gone."""
    window = window or config.RECENT_WINDOW_TURNS * 3
    recent = all_turns[-window:]
    history = "\n".join(f"{t['speaker']}: {t['text']}" for t in recent)
    response = query_call([
        {"role": "system", "content": "Answer the question from the recent conversation."},
        {"role": "user", "content": f"RECENT CONVERSATION:\n{history}\n\nQUESTION: {question}"}
    ])
    return {
        "answer": response,
        "tokens_est": estimate_tokens(history) + estimate_tokens(response) + 50,
        "turns_included": len(recent),
        "turns_dropped": len(all_turns) - len(recent),
    }
